### ISSUE TITLE
api and token

### ISSUE THREAD

**Issue by christian-rauch** [qt-creator/deploy-qtc-plugin#14]
The action requires setting a `api` and `token` but it is not clear from the documentation where to get these values. The example is missing the `api` input and the link behind "API token" is broken.

The plugin template in Qt Creator creates a workflow with:
```yaml
- name: Release on Extension Store
  continue-on-error: true
  uses: qt-creator/deploy-qtc-plugin@v0.3
  with:
    api: ${{ secrets.EXTENSION_STORE_API_URL }}
    token: ${{ secrets.EXTENSION_STORE_API_TOKEN }}
    publish: true
    spec: release/${{ env.PLUGIN_NAME }}.json
    download-url-linux-x64: [...]
```
but there are no examples how to set `EXTENSION_STORE_API_URL` and `EXTENSION_STORE_API_TOKEN`.

Some plugins already seem to use this workflow. E.g. the plugin [`cristianadam.dracula`](https://github.com/cristianadam/qt-creator-dracula) uses the template above and has a [passing CI release pipeline](https://github.com/cristianadam/qt-creator-dracula/actions/runs/15797144367/job/44530707731), meaning that `secrets.EXTENSION_STORE_API_URL` and `secrets.EXTENSION_STORE_API_TOKEN` must have been set to something reasonable.
